name: Feature and Bugfix Branch CI

on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

#      - name: Set up Rust
#        uses: actions/setup-rust@v1
#        with:
#          rust-version: stable

      - name: Lint with clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run tests
        run: cargo test --all-features --all-targets

      - name: Build
        run: cargo build --release